[package]
name = "ddog"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lolog = { git = "https://github.com/lookback/lolog-rs.git", rev = "01e1f34" }
once_cell = "1"
regex = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
ureq = { version = "=2.1.0", features = ["json"] }
