[package]
name = "ddog"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
sync = ["ureq"]
async = ["hyper/client", "rustls", "hyper-rustls", "futures"]

[dependencies]
futures = { version = "0.3.21", optional = true }
hyper = { version = "0.14", features = ["client"], optional = true }
hyper-rustls = { version = "0.23.0", optional = true }
lolog = { git = "https://github.com/lookback/lolog-rs.git", rev = "01e1f34" }
once_cell = "1"
regex = { version = "1" }
rustls = { version = "0.20", optional = true }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
ureq = { version = "=2.1.0", features = ["json"], optional = true }
